name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_run:
    workflows: [Pre-commit]
    types: [completed]
env:
  AZR_REPO_NAME: pre-commit
  ACR_SERVER: midocker.azurecr.io
  ACR_USERNAME: midocker

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Setup image tag
        run: echo "IMAGE_TAG=${ACR_SERVER}/${AZR_REPO_NAME}" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: '.'
          push: true
          file: Dockerfile
          tags: ${{ env.IMAGE_TAG }}
          no-cache: true
        - name: summary
          run: |
            echo "Built and pushed image: \`${{ env.IMAGE_TAG }}\`" >> $GITHUB_STEP_SUMMARY
